[package]
name = "moko-mkl62ba-at-commands"
version = "0.1.0"
edition = "2021"
authors = ["Michael van Niekerk <mike@agri-io.co.za>"]
description = "AT commands client builder for the Shenzen Ai-Thinker Ra08h"
license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["no_std", "moko", "MKL62BA"]

categories = ["no-std", "embedded"]

[dependencies]
atat = { git = "https://github.com/mvniekerk/atat.git", commit = "7bb16dbebe0ec493fd6fa444f811182da98d9654" }
atat_derive = { git = "https://github.com/mvniekerk/atat.git", commit = "7bb16dbebe0ec493fd6fa444f811182da98d9654" }
serde_at = { git = "https://github.com/mvniekerk/atat.git", commit = "7bb16dbebe0ec493fd6fa444f811182da98d9654" }
nb = { version = "1" }
heapless = "0.7"
defmt = { version = "0.3" }