[package]
name = "moko-mkl62ba-at-commands"
version = "0.1.0"
edition = "2021"
authors = ["Michael van Niekerk <mike@agri-io.co.za>"]
description = "AT commands for the Moko MKL62BA"
license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["no_std", "moko", "MKL62BA"]

categories = ["no-std", "embedded"]

[dependencies]
atat = { git = "https://github.com/mvniekerk/atat.git", commit = "4b70c0221e6a66b11868cd921aea802f4403e391", default-features=false, features = ["derive", "bytes", "hex_str_arrays"] }
atat_derive = { git = "https://github.com/mvniekerk/atat.git", commit = "4b70c0221e6a66b11868cd921aea802f4403e391" }
serde_at = { git = "https://github.com/mvniekerk/atat.git", commit = "4b70c0221e6a66b11868cd921aea802f4403e391" }
nb = { version = "1" }
heapless = "0.7"
defmt = { version = "0.3" }

[features]
debug = ["atat/defmt"]
async = ["atat/async"]
default = ["debug", "async"]